platform:ios,'8.0'

target 'DouYu' do

use_frameworks!

pod 'AFNetworking', '~> 3.1.0'

pod 'ReactiveCocoa', '~> 5.0.0-alpha.3'

pod 'Masonry', '~> 1.0.2'

pod 'SDWebImage', '~> 4.0.0-beta2'

pod 'MJRefresh', '~> 3.1.12'


end

